# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-03 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='age',
            new_name='password',
        ),
    ]
